### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by olljanat** [Jason-ZW/open-vm-tools#1]
Can you please add license to this one so I can fork it and use on other projects?

**Comment by olljanat** [comment]
ping @Jason-ZW

**Comment by Jason-ZW** [comment]
@olljanat done

**Comment by olljanat** [comment]
@Jason-ZW empty file? Would be nice to have same Apache 2 license than on all Rancher repos.

**Comment by Jason-ZW** [comment]
@olljanat  done

**Comment by olljanat** [comment]
Ahaa. I see that you added comment which points original source and it is licensed under Apache 2. Thanks.
